name: test-and-lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: make lint