name: test-and-lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: poetry run pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: poetry run flake8 gendiff